class Operator:
    default = "default"
    de_rand1 = "de_rand1"
    de_best1 = "de_best1"
    de_c2best1 = "de_c2best1"
    de_best2 = "de_best2"
    de_rand2 = "de_rand2"
    jaya_classic = "jaya_classic"
    jaya_rand = "jaya_rand"
    pso_classic = "pso_classic"
    sa_classic = "sa_classic"
    ga_x_pmx = "ga_x_pmx"
    ga_x_ox = "ga_x_ox"
    ga_x_tsp_h = "ga_x_tsp_h"
    ga_m_tpe = "ga_m_tpe"
    ga_m_insert = "ga_m_insert"
    ga_m_sub_reverse = "ga_m_sub_reverse"
    ga_s_roulette = "ga_s_roulette"
    ga_s_champion2 = "ga_s_champion2"


class Name:
    de = "de"
    jaya = "jaya"
    pso = "pso"
    sa = "sa"
    ga_x = "ga_x"
    ga_m = "ga_m"
    ga_s = "ga_s"
    ts = "ts"
    do = "do"
